"""empty message

Revision ID: 010dee21d548
Revises: 9aa7172354e9
Create Date: 2024-03-16 10:17:15.219673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010dee21d548'
down_revision = '9aa7172354e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
