"""empty message

Revision ID: 959d7588d660
Revises: 010dee21d548
Create Date: 2024-03-16 23:42:00.646685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959d7588d660'
down_revision = '010dee21d548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###
